### ISSUE TITLE
With empty filter.txt, the game will crash with `Rendering screen`

### ISSUE THREAD

**Issue by Jack-Works** [Librazy/TooltipFilter#2]
Left filter.txt empty (this looks like to be a default option), after I open the inventory, the game will crash with 
```log
java.lang.NullPointerException: Rendering screen
	at org.librazy.tooltipfilter.TooltipFilter.ItemTooltipEvent(TooltipFilter.java:184)
```

After I save the filter with this in the wiki, this mod works.

```yaml
- !filter {
    isFullText: false,
    isRegBase64: true,
    mode: REMOVE_ALL_BUT_LAST_EXACT,
    name: combine_same_attr,
    regExp: XqHsWzAtOWEtZkEtRl1cc1srLV1cZCslP1xzLisk,
    replace: ''
}
- !filter {
    isFullText: true,
    isRegBase64: true,
    mode: REPLACE,
    name: remove_empty_line,
    regExp: KD9tcykuXiguP9TaLnsyfcqxo7opJA==,
    replace: JDE=
}
- !filter {
    isFullText: false,
    isRegBase64: true,
    mode: COMBINE_NEAR_MATCH,
    name: combine_empty_line,
    regExp: XlxzKiQ=,
    replace: ''
}
- !filter {
    isFullText: true,
    isRegBase64: true,
    mode: REPLACE,
    name: combine_hand,
    regExp: KD9tcyleKNTaKSguKcrWKMqxo7opJC5e1NooLsrWKcqxo7ok,
    replace: JDEkMiQ0JDM=
}
```
